### ISSUE TITLE
PINA does not get computed in prepare.community_similarity_data.R

### ISSUE THREAD

**Issue by karchern** [defleury/Schmidt_et_al_2016_community_similarity#3]
both call community.similarity.corr.par (which computes TINA). Needs fix.

**Comment by defleury** [comment]
The call to the same function is correct. The difference is in the "S" matrix provided: TINA will take a SparCC-based S matrix, PINA will take one based on cophenetic distances. In the uploaded code this is indeed a bug. In the script used for the original paper, the correct S matrix was used.

Fixed by replacing `S.sparcc` w/ `S.phylo` in the code.
